(()=>{
const KEY='mk-debt-live-v2';
const $=id=>document.getElementById(id),N=x=>Number(x)||0,T=()=>new Date().toISOString().slice(0,10),M=(n,c)=>N(n).toLocaleString()+' '+c,E=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let d;try{d=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){} if(!d||!Array.isArray(d.people))d={rate:10,currency:'MMK',people:[],payments:[]}; if(!Array.isArray(d.payments))d.payments=[]; let cur=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(d));
function ip(p){if(p.stop)return 0;const a=new Date((p.date||T())+'T00:00:00'),b=new Date();const m=Math.max(0,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth());const paid=d.payments.filter(x=>x.pid===p.id).reduce((s,x)=>s+N(x.interest),0);return Math.max(0,N(p.amount)*N(p.rate)/100*m-paid)}
function pp(p){return d.payments.filter(x=>x.pid===p.id).reduce((s,x)=>s+N(x.principal),0)}
function bal(p){return Math.max(0,N(p.amount)-pp(p)+ip(p))}
function toast(s){const e=$('toast');if(!e)return;e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function nav(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const e=$(id);if(e)e.classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));render(id);scrollTo(0,0)}
function person(p){return `<div class="person" data-r-action="detail" data-id="${p.id}"><div class="avatar">${E((p.name||'?')[0])}</div><div class="grow"><b>${E(p.name)}</b><small>${E(p.phone||'-')} · ${p.currency}</small></div><div class="right"><b>${M(bal(p),p.currency)}</b><small class="muted">ကျန်</small></div></div>`}
function dashboard(){const mmk=d.people.filter(p=>p.currency==='MMK').reduce((s,p)=>s+bal(p),0),thb=d.people.filter(p=>p.currency==='THB').reduce((s,p)=>s+bal(p),0),lm=d.people.filter(p=>p.currency==='MMK').reduce((s,p)=>s+N(p.amount),0),lt=d.people.filter(p=>p.currency==='THB').reduce((s,p)=>s+N(p.amount),0),pm=d.people.filter(p=>p.currency==='MMK').reduce((s,p)=>s+pp(p),0),pt=d.people.filter(p=>p.currency==='THB').reduce((s,p)=>s+pp(p),0);$('dashboard').innerHTML=`<div class="card hero"><div class="row"><div><div class="muted">MK DEBT · OWNER</div><h2>ချေးငွေ စီမံခန့်ခွဲမှု</h2><p class="muted">Loan · Interest · Payment</p></div><div class="logo">💎</div></div></div><div class="glass-stats"><div class="glass-stat"><span class="ico">💰</span><small>Total Loan</small><b>${M(lm,'MMK')}</b><small>${M(lt,'THB')}</small></div><div class="glass-stat"><span class="ico">📊</span><small>Total Paid</small><b>${M(pm,'MMK')}</b><small>${M(pt,'THB')}</small></div><div class="glass-stat"><span class="ico">◔</span><small>Remaining</small><b>${M(mmk,'MMK')}</b><small>${M(thb,'THB')}</small></div></div><div class="quick-grid"><button class="quick" data-r-page="newloan"><span class="qico">➕</span>Add Loan</button><button class="quick" data-r-page="borrowers"><span class="qico">👥</span>Borrowers</button><button class="quick" data-r-page="payments"><span class="qico">💳</span>Payment</button><button class="quick" data-r-page="reports"><span class="qico">📈</span>Reports</button></div><div class="card"><div class="field"><input id="rsearch" type="search" placeholder="🔍 Search borrower..."></div></div><div class="card"><div class="row"><h3>👥 Borrowers · ${d.people.length}</h3><button class="btn" data-r-page="borrowers">View All</button></div><div id="rpeople">${d.people.slice().reverse().map(person).join('')||'<div class="empty">စာရင်းမရှိသေးပါ</div>'}</div></div>`;$('rsearch')?.addEventListener('input',()=>{const q=$('rsearch').value.toLowerCase();$('rpeople').innerHTML=d.people.filter(p=>(p.name+' '+(p.phone||'')).toLowerCase().includes(q)).map(person).join('')||'<div class="empty">မတွေ့ပါ</div>'})}
function newloan(){$('newloan').innerHTML=`<div class="card"><div class="row"><h2>➕ Add Loan</h2><button class="btn" data-r-page="dashboard">×</button></div><div class="field"><label>အမည် *</label><input id="rn"></div><div class="field"><label>ဖုန်း</label><input id="rp" type="tel"></div><div class="grid"><div class="field"><label>ငွေပမာဏ *</label><input id="ra" type="number" inputmode="decimal"></div><div class="field"><label>Currency</label><select id="rc"><option>MMK</option><option>THB</option></select></div></div><div class="grid"><div class="field"><label>ချေးသည့်ရက်</label><input id="rd" type="date" value="${T()}"></div><div class="field"><label>အတိုး % / လ</label><input id="rr" type="number" value="${d.rate||10}" step="0.1"></div></div><div class="field"><label>လစဉ်ပေးငွေ</label><input id="rm" type="number"></div><button class="btn green" data-r-action="saveLoan">✓ Save Loan</button><button class="btn" data-r-page="dashboard">Cancel</button></div>`}
function borrowers(){const list=d.people.map(person).join('')||'<div class="empty">Borrower မရှိသေးပါ</div>';$('borrowers').innerHTML=`<div class="card"><h2>👥 Borrowers</h2><div class="field"><input id="rbsearch" placeholder="အမည် / ဖုန်း ရှာရန်"></div><div id="rblist">${list}</div></div>`;$('rbsearch')?.addEventListener('input',()=>{const q=$('rbsearch').value.toLowerCase();$('rblist').innerHTML=d.people.filter(p=>(p.name+' '+(p.phone||'')).toLowerCase().includes(q)).map(person).join('')||'<div class="empty">မတွေ့ပါ</div>'})}
function payments(){$('payments').innerHTML=`<div class="card"><h2>💳 Payment</h2>${d.people.map(p=>`<div class="person"><div class="avatar">${E((p.name||'?')[0])}</div><div class="grow"><b>${E(p.name)}</b><small>${M(bal(p),p.currency)} ကျန်</small></div><button class="btn green" style="width:auto" data-r-action="pay" data-id="${p.id}">ပေးချေ</button></div>`).join('')||'<div class="empty">Borrower မရှိသေးပါ</div>'}</div>`}
function pay(id){const p=d.people.find(x=>x.id===id);if(!p)return;cur=id;const b=bal(p),i=Math.min(b,ip(p)),a=Math.min(b,N(p.monthly)||b),pr=Math.max(0,a-i);$('payments').innerHTML=`<div class="card"><div class="row"><h2>💳 ${E(p.name)}</h2><button class="btn" data-r-page="payments">←</button></div><div class="card"><div class="muted">လက်ကျန်</div><div class="big">${M(b,p.currency)}</div></div><div class="field"><label>ပေးချေငွေ *</label><input id="rpa" type="number" inputmode="decimal" value="${a||''}" max="${b}"></div><div class="field"><label>အတိုး</label><input id="rpi" type="number" value="${i}"></div><div class="field"><label>အရင်း</label><input id="rpp" type="number" value="${pr}"></div><button class="btn green" data-r-action="savePay" data-id="${id}">✓ Save Payment</button><button class="btn" data-r-page="payments">Cancel</button></div>`;const sync=()=>{let x=Math.min(b,N($('rpa')?.value)),y=Math.min(x,Math.max(0,N($('rpi')?.value)));$('rpi').value=y;$('rpp').value=Math.max(0,x-y)};$('rpa').oninput=sync;$('rpi').oninput=sync;sync()}
function detail(id){const p=d.people.find(x=>x.id===id);if(!p)return;cur=id;const rows=d.payments.filter(x=>x.pid===id).slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${M(x.amount,p.currency)}</td><td>${M(x.interest,p.currency)}</td><td>${M(x.principal,p.currency)}</td></tr>`).join('')||'<tr><td colspan="4">Payment မရှိသေးပါ</td></tr>';$('detail').innerHTML=`<div class="card"><div class="row"><h2>👤 ${E(p.name)}</h2><button class="btn" data-r-page="borrowers">←</button></div><div class="grid"><div class="card"><div class="muted">Loan</div><div class="big">${M(p.amount,p.currency)}</div></div><div class="card"><div class="muted">ကျန်</div><div class="big">${M(bal(p),p.currency)}</div></div></div><p class="muted">Phone: ${E(p.phone||'-')} · ${p.rate}% / လ</p><button class="btn primary" data-r-action="pay" data-id="${id}">💳 Payment</button><button class="btn danger" data-r-action="delete" data-id="${id}">🗑 Delete</button></div><div class="card"><h3>Payment History</h3><div class="table"><table><thead><tr><th>ရက်</th><th>ပေးငွေ</th><th>အတိုး</th><th>အရင်း</th></tr></thead><tbody>${rows}</tbody></table></div></div>`}
function reports(){$('reports').innerHTML=`<div class="card"><h2>📈 Reports</h2><div class="grid"><div class="card"><div class="muted">MMK Loan</div><div class="big">${M(d.people.filter(p=>p.currency==='MMK').reduce((s,p)=>s+N(p.amount),0),'MMK')}</div></div><div class="card"><div class="muted">THB Loan</div><div class="big">${M(d.people.filter(p=>p.currency==='THB').reduce((s,p)=>s+N(p.amount),0),'THB')}</div></div></div><p>Borrowers: <b>${d.people.length}</b></p><p>Payments: <b>${d.payments.length}</b></p></div>`}
function settings(){$('settings').innerHTML=`<div class="card"><h2>⚙ Settings</h2><div class="field"><label>Default Interest % / လ</label><input id="rsr" type="number" value="${d.rate||10}"></div><div class="field"><label>Default Currency</label><select id="rsc"><option ${d.currency==='MMK'?'selected':''}>MMK</option><option ${d.currency==='THB'?'selected':''}>THB</option></select></div><button class="btn green" data-r-action="saveSettings">✓ Save Settings</button></div>`}
function render(id){({dashboard,newloan,borrowers,payments,reports,settings,detail}[id]||dashboard)()}
document.addEventListener('click',e=>{const p=e.target.closest('[data-r-page]');if(p){nav(p.dataset.rPage);return}const a=e.target.closest('[data-r-action]');if(!a)return;const id=a.dataset.id;switch(a.dataset.rAction){case'detail':detail(id);nav('detail');break;case'pay':pay(id);nav('payments');break;case'saveLoan':{const n=$('rn').value.trim(),amt=N($('ra').value);if(!n||amt<=0)return toast('အမည်နဲ့ ငွေပမာဏ ထည့်ပါ');const p={id:'p'+Date.now(),name:n,phone:$('rp').value,amount:amt,currency:$('rc').value,date:$('rd').value||T(),rate:N($('rr').value)||10,monthly:N($('rm').value),stop:false};d.people.push(p);save();cur=p.id;toast('ချေးငွေ သိမ်းပြီးပါပြီ ✓');nav('detail');detail(p.id);break}case'savePay':{const p=d.people.find(x=>x.id===id);const amt=N($('rpa').value),ii=N($('rpi').value),pr=N($('rpp').value);if(!p||amt<=0)return toast('ပေးချေငွေထည့်ပါ');if(ii+pr>amt)return toast('အတိုး + အရင်း မကျော်ပါစေနဲ့');d.payments.push({id:'q'+Date.now(),pid:p.id,amount:amt,interest:ii,principal:pr,date:T()});save();toast('Payment သိမ်းပြီးပါပြီ ✓');nav('detail');detail(p.id);break}case'delete':if(confirm('ဒီ Borrower ကို ဖျက်မလား?')){d.people=d.people.filter(p=>p.id!==id);d.payments=d.payments.filter(x=>x.pid!==id);save();nav('borrowers')}break;case'saveSettings':d.rate=N($('rsr').value)||10;d.currency=$('rsc').value;save();toast('Settings သိမ်းပြီးပါပြီ ✓');nav('dashboard')}}});
window.MKDebtRescue={nav,pay,detail};
render('dashboard');
})();